---
collections:

 - name: amazon.aws
   source: "https://galaxy.ansible.com"

 - name: community.aws
   source: "https://galaxy.ansible.com"

 - name: awx.awx
   source: "https://galaxy.ansible.com"

 - name: ansible.controller
   source: "https://galaxy.ansible.com"
