---
collections:

 - name: amazon.aws
   source: "https://galaxy.ansible.com"

 - name: community.aws
   source: "https://galaxy.ansible.com"

 - name: redhat_cop.controller_configuration
   source: "https://galaxy.ansible.com"
