---
- hosts: all
  become: True
  tasks:
      - name: Ensure directory exists
        file:
            path: /tmp/tower-demo
            state: directory
            owner: root
            group: sys
            mode: '0755'
        tags:
        - directory
        
    - name: generate empty files
      file:
        path: "/tmp/tower-demo/file{{ item }}"
        state: touch
        owner: root
        group: 'sys'
        mode: '0644'
      with_sequence: start=1 end={{ count }}