--- 
- hosts: localhost
  gather_facts: no
  become: no
  tasks:
    - name: Ensure directory exists
      file:
        path: /tmp/tower-demo
        state: directory
        owner: frank
        group: frank
        mode: '0755'
      tags:
       - directory
        
    - name: generate empty files
      file:
        path: "/tmp/tower-demo/file{{ item }}"
        state: touch
      with_sequence: start=1 end={{ count }}