---
- hosts: all
  vars:
       filecount: 3
  become: True
  
  tasks:
    - name: Ensure directory exists
      file:
        path: /tmp/tower-demo
        state: directory
        owner: root
        group: sys
        mode: '0755'
        
  tasks:
    - name: Create x amount of files
      file:
        path: "/tmp/tower-demo/git-{{ item }}"
        state: touch
        owner: root
        group: 'sys'
        mode: '0644'
      with_sequence: start=1 end={{ filecount }}