---
- hosts: all
  become: True
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: filecount
    - name: Ensure directory exists
      file:
        path: /tmp/tower-demo
        state: directory
        owner: root
        group: sys
        mode: '0755'
    
    - name: Create x amount of files
      file:
        path: "/tmp/tower-demo/git-{{ item }}"
        state: touch
        owner: root
        group: 'sys'
        mode: '0644'
      with_sequence: start=1 end={{ filecount }}
      register: files_created
      
    - name: Delete all other files
      file:
        path: "/tmp/tower-demo/"
        state: absent
      with_items: "{{ files_created['files'] }}"