---
- hosts: all
  become: True
  vars:
    new_files: []
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: filecount
    - name: Ensure directory exists
      file:
        path: /tmp/tower-demo
        state: directory
        owner: root
        group: sys
        mode: '0755'
    
    - name: Create x amount of files
      file:
        path: "/tmp/tower-demo/git-{{ item }}"
        state: touch
        owner: root
        group: 'sys'
        mode: '0644'
      with_sequence: start=1 end={{ filecount }}
      register: files_created
      
    - name: Print output
      debug:
        var: files_created
        
    - name: Add new files to array
      set_fact:
        new_files: "{{ files_created.results | map(attributes='dest') | list }}"
        
    - debug: var=new_files

    - name: Get other files
      find:
        path: /tmp/tower-demo
        excludes:
          - "{{ new_files }}"
      register: files_to_delete
      
    - name: What did we do
      debug:
        var: files_to_delete