---
- hosts: all
  become: True
  tasks:
    - name: Display all variables/facts known for a host
      debug:
        var: groupvars[filecount]
        verbosity: 4
    - name: Ensure directory exists
      file:
        path: /tmp/tower-demo
        state: directory
        owner: root
        group: sys
        mode: '0755'
    
    - name: Create x amount of files
      file:
        path: "/tmp/tower-demo/git-{{ item }}"
        state: touch
        owner: root
        group: 'sys'
        mode: '0644'
      with_sequence: start=1 end={{ filecount }}