---
- hosts: all
  become: True
  tasks:
      - name: Ensure directory exists
        file:
            path: /tmp/testdir
            state: directory
            owner: root
            group: sys
            mode: '0755'
        tags:
        - directory
            
      - name: Copy file1 to directory
        copy:
            src: /tower-demo/testfile-1.conf
            dest: /tmp/testdir/testfile-1.conf
            owner: root
            group: 'sys'
            mode: '0644'
        tags:
        - file1
            
      - name: Copy file2 to directory
        copy:
            src: /tower-demo/testfile-2.conf
            dest: /tmp/testdir/testfile-2.conf
            owner: root
            group: 'sys'
            mode: '0644'
        tags:
        - file2
            
      - name: Copy file3 to directory
        copy:
            src: /tower-demo/testfile-3.conf
            dest: /tmp/testdir/testfile-3.conf
            owner: root
            group: 'sys'
            mode: '0644'
        tags:
        - file3