---
- name: Create AWS instances
  hosts: localhost
  collections:
   - awx.awx
   - ansible.controller
  vars:
   region: eu-west-1
   controller_hostname: 10.243.64.4
   controller_validate_certs: false
  tasks:
   - name: Get EC2 Instances
     ec2_instance_info:
      region: "{{ region }}"
      filters:
       instance-state-name: [ "running"]
     register: ec2_node_info

   - name: Add instance to webfarm group
     group:
      name: Webfarm
      inventory: "AWS Inventory"
      state: present
      controller_host: "{{ controller_hostname }}"
      hosts:
       - "{{ item.public_dns_name }}"
      children:
       - Webserver
       - Database
      preserve_existing_hosts: True
      preserve_existing_children: True
     loop: "{{ ec2_node_info.instances }}"

   - name: Add instance to specific group
     group:
      name: "{{ item.name }}"
      inventory: "AWS Inventory"
      controller_host: "{{ controller_hostname }}"
      hosts:
       - "{{ item.public_dns_name }}"
      preserve_existing_hosts: True
     loop: "{{ ec2_node_info.instances }}"
