---
- name: Create AWS inventory groups
  hosts: localhost
  collections:
   - awx.awx
   - ansible.controller
  vars:
   controller_hostname: 10.243.64.4
   controller_validate_certs: false
  tasks:
   - name: Creating the groups
     group:
      name: {{ item }}
      inventory: "AWS Inventory"
      state: present
      controller_host: "{{ controller_hostname }}"
      preserve_existing_hosts: True
     loop:
        - webserver
        - database
        - loadbalancer
