---
- name: Create AWS instances
  hosts: localhost
  collections:
   - awx.awx
   - ansible.controller
  vars:
   keypair: key-frank-west
   instance_type: t2.micro
   image: ami-5b2e5722
   region: eu-west-1
   count: []
   type: []
   controller_hostname: 10.243.64.4
   controller_validate_certs: false
  tasks:
   - name: Add security group rule descriptions
     ec2_group:
      name: "{{ type }}"
      description: Webservers SC
      vpc_id: vpc-46e8ea20
      region: "{{ region }}"
      rules:
       - proto: tcp
         ports:
          - 22
          - 80
         cidr_ip: 0.0.0.0/0

   - name: Launch instance
     ec2:
      key_name: "{{ keypair }}"
      group: "{{ type }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: true
      assign_public_ip: yes
      vpc_subnet_id: subnet-0deda245
      region: "{{ region }}"
      count: "{{ count }}"
      instance_tags:
       Name: "{{ type }}"
     register: ec2
  
   - name: Update AWX Inventory
     awx.awx.inventory_source:
      name: AWS
      inventory: "AWS Inventory"
      description: AWS EC2 for demo purposes
      credential: AWS
      overwrite: True
      update_on_launch: True
      organization: Default
      controller_host: "{{ controller_hostname }}"
      source: ec2
      state: present

   - name: Add instance to webfarm group
     group:
      name: Webfarm
      inventory: "AWS Inventory"
      state: present
      controller_host: "{{ controller_hostname }}"
      hosts:
       - "{{ item.dns_name }}"
      children:
       - Webserver
       - Database
      preserve_existing_hosts: True
      preserve_existing_children: True
     loop: "{{ ec2.instances }}"

   - name: Add instance to specific group
     group:
      name: "{{ type }}"
      inventory: "AWS Inventory"
      controller_host: "{{ controller_hostname }}"
      hosts:
       - "{{ item.dns_name }}"
      preserve_existing_hosts: True
     loop: "{{ ec2.instances }}"
