---
- name: Create AWS instances
  hosts: localhost
  collections:
   - awx.awx
   - ansible.controller
  vars:
   region: eu-west-1
   controller_hostname: 10.243.64.4
   controller_validate_certs: false
  tasks:
   - name: Update AWX Inventory
     awx.awx.inventory_source:
      name: AWS
      inventory: "AWS Inventory"
      description: AWS EC2 for demo purposes
      credential: AWS
      overwrite: yes
      update_on_launch: no
      organization: Default
      controller_host: "{{ controller_hostname }}"
      source: ec2
      state: present

   - name: Add instance to webfarm group
     group:
      name: Webfarm
      inventory: "AWS Inventory"
      state: present
      controller_host: "{{ controller_hostname }}"
      hosts:
       - "{{ item.dns_name }}"
      children:
       - Webserver
       - Database
      preserve_existing_hosts: True
      preserve_existing_children: True
     loop: "{{ ec2.instances }}"

   - name: Add instance to specific group
     group:
      name: "{{ item.name }}"
      inventory: "AWS Inventory"
      controller_host: "{{ controller_hostname }}"
      hosts:
       - "{{ item.dns_name }}"
      preserve_existing_hosts: True
     loop: "{{ ec2.instances }}"
