---
- hosts: localhost
  gather_facts: False
  vars:
    keypair: key-frank-west
    instance_type: t2.micro
    image: ami-5b2e5722
    region: eu-west-1
    count: []
  tasks:
    - name: Launch webserver instance
      ec2:
         key_name: "{{ keypair }}"
         group: webserver
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         assign_public_ip: yes
         vpc_subnet_id: subnet-0deda245
         region: "{{ region }}"
         count: "{{ count }}"
         instance_tags:
            Name: Webserver
      register: ec2