- name: Restart the Homebridge container
  hosts: all
  become: yes
  tasks:
      - name: Restart Homebridge container
        docker_container:
            name: homebridge_homebridge_1
            image: oznu/homebridge:raspberry-pi
            state: started
            restart: yes
